repos:
  - repo: local
    hooks:
      - id: format
        name: Format
        language: system
        entry: bazel run //:format
        files: .*
      - id: lint
        name: Lint
        language: system
        entry: bazel lint --fix //...
        files: .*
