name: Build and test
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up the cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE', 'environment.yml', '**/*.bazel', '**/*.bzl') }}
          restore-keys: ${{ runner.os }}-bazel-

      - name: Workaround for failing to find lint dependencies
        run: bazel build lib   

      - name: Check for linting errors
        run: bazel run @aspect_rules_format//format -- --mode check

      - name: Build all targets and run all tests
        run: bazel test //...
