name: Publish
on:
  push:
    tags:
      - '**'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip CI')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set up the cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE', 'environment.yml', '**/*.bazel', '**/*.bzl') }}
          restore-keys: ${{ runner.os }}-bazel-
      - name: Run the release procedure
        run: ./publish.sh
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
