# https://docs.github.com/en/actions
name: "Release"
on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"
jobs:
  release:
    name: "Release"
    if: "!contains(github.event.head_commit.message, 'skip CI')"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Create release"
        uses: "ergebnis/.github/actions/github/release/create@1.8.0"
        with:
          github-token: ${{ secrets.GH_TOKEN }}
